name: CI-Vibhu

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  pull-requests: write

jobs:
  ci:
    uses: aristanetworks/avd/.github/workflows/release-note-labeler.yml@devel
    
